// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertVideo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertVideo'](arg1, arg2, arg3);
}

export function GetLastDestination() {
  return window['go']['main']['App']['GetLastDestination']();
}

export function SelectDestinationFolder() {
  return window['go']['main']['App']['SelectDestinationFolder']();
}

export function SelectVideoFiles() {
  return window['go']['main']['App']['SelectVideoFiles']();
}
