// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertVideo(arg1:string,arg2:string,arg3:number):Promise<void>;

export function GetLastDestination():Promise<string>;

export function SelectDestinationFolder():Promise<string>;

export function SelectVideoFiles():Promise<Array<main.VideoInfo>>;
